// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uomehuvltpryikyyxcxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvbWVodXZsdHByeWlreXl4Y3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTA3NTYsImV4cCI6MjA2NDQ2Njc1Nn0.Ke0fAjd8rt2WXyWUsyQKTLwngL_H5RkE9GID8oqUpPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);